name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Clean cache
        run: npm cache clean --force
      - name: delete package-lock.json
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Run Automated Test
        run: npm test -- --coverage
        env:
          CI: true
